sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t spaceboy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true spaceboy/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react3"
  env: "Dockerreact3-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-908885700562"
  bucket_path: "docker-react3"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY